# Generated by Django 3.0.3 on 2022-09-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='new',
        ),
    ]
