# Generated by Django 3.0.3 on 2022-09-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_issue_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
