# Generated by Django 3.0.3 on 2022-09-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220914_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='current_status',
            field=models.CharField(default='Open', max_length=20),
        ),
    ]
