# Generated by Django 3.0.3 on 2022-09-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('watcher_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_id', models.IntegerField()),
                ('user_id', models.CharField(max_length=60)),
            ],
        ),
    ]
