# Generated by Django 3.0.3 on 2022-09-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueEstimatedTime',
            fields=[
                ('issue_estimated_time_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_id', models.IntegerField()),
                ('estimated_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worklog',
            fields=[
                ('worklog_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_id', models.IntegerField()),
                ('user_id', models.CharField(max_length=50)),
                ('estimated_time', models.IntegerField(blank=True, null=True)),
                ('logged_time', models.IntegerField()),
            ],
        ),
    ]
